### ISSUE TITLE
Usage example

### ISSUE THREAD

**Issue by bookmoons** [ProtonMail/libsieve-php#9]
Is there an example of usage of this library?

I'd like to use it to add mail filtering to nextcloud https://github.com/nextcloud/mail/issues/44.

**Comment by ThHareau** [comment]
Hi @bookmoons 
We just updated the readme to include two examples. Could you have a look?

**Comment by bookmoons** [comment]
Thanks a lot for the extensive examples. Will be going over them in detail to help with this.

**Comment by bookmoons** [comment]
Thanks a lot for the extensive examples. Will be going over them in detail to help with this.
